'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AUX_SYSTEM
    Public Property SystemId As Decimal
    Public Property SystemName As String
    Public Property Version As String
    Public Property systemPrefix As String
    Public Property CompanyEntity_Code As String

End Class
