'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOM_Customer
    Public Property SystemID As Decimal
    Public Property BranchSourceCode As String
    Public Property CustomerSourceCode As String
    Public Property CustomerSourceName As String
    Public Property CustomerID As Nullable(Of Integer)
    Public Property KeyAccountID As Nullable(Of Integer)
    Public Property CustomerKey_SystemOnly As Nullable(Of Integer)

End Class
