'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOM_ProductGroup
    Public Property SystemID As Decimal
    Public Property PGroupSourceCode As String
    Public Property PGroupSourceName As String
    Public Property ProductGroupID As Nullable(Of Integer)

End Class
