'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOM_TypeRoute
    Public Property SystemID As Decimal
    Public Property TypeRouteSourceCode As String
    Public Property TypeRouteSourceName As String
    Public Property TypeRouteID As Nullable(Of Integer)
    Public Property BranchSourceCode As String

End Class
