'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOM_Products
    Public Property SystemID As Decimal
    Public Property ProductSourceCode As String
    Public Property ProductSourceName As String
    Public Property ProductID As Nullable(Of Integer)
    Public Property ProductKey_SystemOnly As Nullable(Of Integer)

End Class
