'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOM_Brand
    Public Property SystemID As Decimal
    Public Property BrandSourceCode As String
    Public Property BrandSourceName As String
    Public Property BrandID As Nullable(Of Integer)
    Public Property CategoryID As Nullable(Of Integer)
    Public Property UnionSourceCode As String

End Class
