'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SalesStagingContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SalesStagingContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property HOM_Branch() As DbSet(Of HOM_Branch)
    Public Overridable Property HOM_Brand() As DbSet(Of HOM_Brand)
    Public Overridable Property HOM_Category() As DbSet(Of HOM_Category)
    Public Overridable Property HOM_Chain() As DbSet(Of HOM_Chain)
    Public Overridable Property HOM_Channel() As DbSet(Of HOM_Channel)
    Public Overridable Property HOM_Customer() As DbSet(Of HOM_Customer)
    Public Overridable Property HOM_CustomerCategory() As DbSet(Of HOM_CustomerCategory)
    Public Overridable Property HOM_District() As DbSet(Of HOM_District)
    Public Overridable Property HOM_Flavor() As DbSet(Of HOM_Flavor)
    Public Overridable Property HOM_PayMethod() As DbSet(Of HOM_PayMethod)
    Public Overridable Property HOM_Presentation() As DbSet(Of HOM_Presentation)
    Public Overridable Property HOM_ProductGroup() As DbSet(Of HOM_ProductGroup)
    Public Overridable Property HOM_Products() As DbSet(Of HOM_Products)
    Public Overridable Property HOM_Reason() As DbSet(Of HOM_Reason)
    Public Overridable Property HOM_Size() As DbSet(Of HOM_Size)
    Public Overridable Property HOM_Source() As DbSet(Of HOM_Source)
    Public Overridable Property HOM_SubBrand() As DbSet(Of HOM_SubBrand)
    Public Overridable Property HOM_SubCategory() As DbSet(Of HOM_SubCategory)
    Public Overridable Property HOM_TypeBrand() As DbSet(Of HOM_TypeBrand)
    Public Overridable Property HOM_TypeRoute() As DbSet(Of HOM_TypeRoute)
    Public Overridable Property HOM_TypeSales() As DbSet(Of HOM_TypeSales)
    Public Overridable Property HOM_Country() As DbSet(Of HOM_Country)
    Public Overridable Property HOM_keyAccount() As DbSet(Of HOM_keyAccount)
    Public Overridable Property HOM_ProdCategory() As DbSet(Of HOM_ProdCategory)
    Public Overridable Property AUX_SYSTEM() As DbSet(Of AUX_SYSTEM)

End Class
