'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BIDimensionsTestContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BIDimensionsTestContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property D01_PRODUCTS() As DbSet(Of D01_PRODUCTS)
    Public Overridable Property HOM_Branch() As DbSet(Of HOM_Branch)
    Public Overridable Property HOM_Brand() As DbSet(Of HOM_Brand)
    Public Overridable Property HOM_Flavor() As DbSet(Of HOM_Flavor)
    Public Overridable Property HOM_Presentation() As DbSet(Of HOM_Presentation)
    Public Overridable Property HOM_ProductGroup() As DbSet(Of HOM_ProductGroup)
    Public Overridable Property HOM_Size() As DbSet(Of HOM_Size)
    Public Overridable Property HOM_Source() As DbSet(Of HOM_Source)
    Public Overridable Property HOM_SubBrand() As DbSet(Of HOM_SubBrand)
    Public Overridable Property HOM_SubCategory() As DbSet(Of HOM_SubCategory)
    Public Overridable Property HOM_TypeBrand() As DbSet(Of HOM_TypeBrand)
    Public Overridable Property M01_Brand() As DbSet(Of M01_Brand)
    Public Overridable Property M01_Category() As DbSet(Of M01_Category)
    Public Overridable Property M01_Flavor() As DbSet(Of M01_Flavor)
    Public Overridable Property M01_POT_Status() As DbSet(Of M01_POT_Status)
    Public Overridable Property M01_Presentation() As DbSet(Of M01_Presentation)
    Public Overridable Property M01_ProductGroup() As DbSet(Of M01_ProductGroup)
    Public Overridable Property M01_Products() As DbSet(Of M01_Products)
    Public Overridable Property M01_Size() As DbSet(Of M01_Size)
    Public Overridable Property M01_Source() As DbSet(Of M01_Source)
    Public Overridable Property M01_SubBrand() As DbSet(Of M01_SubBrand)
    Public Overridable Property M01_SubCategory() As DbSet(Of M01_SubCategory)
    Public Overridable Property M01_TypeBrand() As DbSet(Of M01_TypeBrand)
    Public Overridable Property M01_TypeOFSales() As DbSet(Of M01_TypeOFSales)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)

End Class
