'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOM_Presentation
    Public Property SystemID As Decimal
    Public Property PresentSourceCode As String
    Public Property PresentSourceName As String
    Public Property PresentationID As Nullable(Of Integer)

End Class
