'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class D01_PRODUCTS
    Public Property ProductKey As Integer
    Public Property CountryID As String
    Public Property ProductID As String
    Public Property SAP_ProductCode As String
    Public Property Description As String
    Public Property UnitsPerCase As Nullable(Of Decimal)
    Public Property PresentationID As Nullable(Of Integer)
    Public Property PresentationName As String
    Public Property GroupID As Nullable(Of Integer)
    Public Property GroupName As String
    Public Property SourceID As Nullable(Of Integer)
    Public Property SourceName As String
    Public Property CategoryID As Nullable(Of Integer)
    Public Property CategoryName As String
    Public Property SubCategoryID As Nullable(Of Integer)
    Public Property SubCategoryName As String
    Public Property BrandID As Nullable(Of Integer)
    Public Property BrandName As String
    Public Property SubBrandID As Nullable(Of Integer)
    Public Property SubBrandName As String
    Public Property TypeBrandID As Nullable(Of Integer)
    Public Property TypeBrandName As String
    Public Property SizeID As Nullable(Of Integer)
    Public Property SizeName As String
    Public Property FlavorID As Nullable(Of Integer)
    Public Property FlavorName As String
    Public Property Active_Flag As Nullable(Of Boolean)
    Public Property SystemOnly As Nullable(Of Boolean)
    Public Property Flag_innovation As Nullable(Of Boolean)
    Public Property StartDate_innovation As Nullable(Of Date)
    Public Property EndDate_innovation As Nullable(Of Date)
    Public Property PricePoint As Nullable(Of Decimal)
    Public Property POT_StatusID As Nullable(Of Integer)
    Public Property UnitsForDistribution As Nullable(Of Decimal)
    Public Property TypeSalesID As Nullable(Of Integer)
    Public Property TypeSalesName As String

End Class
