'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class D02_CUSTOMERS
    Public Property CustomerKey As Integer
    Public Property CountryID As String
    Public Property CustomerID As String
    Public Property SAP_CustomerCode As String
    Public Property Customer_Name As String
    Public Property KeyAccountID As Nullable(Of Integer)
    Public Property KeyAccounName As String
    Public Property PayMtID As Nullable(Of Integer)
    Public Property PayMtMthodName As String
    Public Property ChainID As Nullable(Of Integer)
    Public Property ChainName As String
    Public Property CategoryID As Nullable(Of Integer)
    Public Property CategoryName As String
    Public Property WeeklyDROPSize As Nullable(Of Decimal)
    Public Property LastSalesDate As Nullable(Of Date)
    Public Property CreationDate As Nullable(Of Date)
    Public Property Flag_Active As Nullable(Of Boolean)
    Public Property SystemOnly As Nullable(Of Boolean)
    Public Property EventualKey_Client As String
    Public Property Delivery_Area As String

End Class
