'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOM_keyAccount
    Public Property SystemID As Decimal
    Public Property KeyAccountSourceCode As String
    Public Property KeyAccountSourceName As String
    Public Property KeyAccountID As Integer

End Class
