'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOM_SubBrand
    Public Property SystemID As Decimal
    Public Property SubBrandSourceCode As String
    Public Property SubBrandSourceName As String
    Public Property SubBrandID As Nullable(Of Integer)
    Public Property UnionSourceCode As String

End Class
