'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOM_Country
    Public Property SystemID As Decimal
    Public Property CountrySourceCode As String
    Public Property CustomerCode As String
    Public Property CountrySourceName As String
    Public Property CountryId As String
    Public Property BranchId As Nullable(Of Integer)

End Class
