'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOM_RSR
    Public Property SystemID As Decimal
    Public Property RSRSourceCode As String
    Public Property BranchSourceCode As String
    Public Property RSRSourceName As String
    Public Property RSRID As Nullable(Of Integer)

End Class
