'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOM_Chain
    Public Property SystemID As Decimal
    Public Property BranchSourceCode As String
    Public Property ChainSourceCode As String
    Public Property ChainSourceName As String
    Public Property ChainID As Nullable(Of Integer)

End Class
