'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class M05_Geography
    Public Property GeographicKey As Integer
    Public Property CountryID As String
    Public Property BranchID As Nullable(Of Integer)
    Public Property ZoneID As Nullable(Of Integer)
    Public Property MUID As Nullable(Of Integer)
    Public Property RouteID As String
    Public Property DistrictID As Nullable(Of Integer)
    Public Property RSRId As Nullable(Of Integer)
    Public Property TypeRouteID As Nullable(Of Integer)
    Public Property Active_Flag As Nullable(Of Boolean)
    Public Property SystemOnly As Nullable(Of Boolean)

End Class
