'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class D05_GEOGRAPHY
    Public Property GeographicKey As Integer
    Public Property CountryID As String
    Public Property CountryName As String
    Public Property BranchID As Nullable(Of Integer)
    Public Property BranchName As String
    Public Property ZoneID As Nullable(Of Integer)
    Public Property ZoneName As String
    Public Property MUID As Nullable(Of Integer)
    Public Property Market_Unit As String
    Public Property RouteID As String
    Public Property DistrictID As Nullable(Of Integer)
    Public Property DistrictName As String
    Public Property RSRId As Nullable(Of Integer)
    Public Property RSRName As String
    Public Property TypeRouteID As Nullable(Of Integer)
    Public Property TypeRouteName As String
    Public Property Flag_Active As Nullable(Of Boolean)
    Public Property SystemOnly As Nullable(Of Boolean)
    Public Property CIPBINID As Nullable(Of Integer)
    Public Property CIPBINNAME As String

End Class
