'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class M01_SubBrand
    Public Property SubBrandID As Integer
    Public Property SubBrandName As String
    Public Property Active_Flag As Nullable(Of Boolean)
    Public Property SystemOnly As Nullable(Of Boolean)

End Class
