'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class M05_Route_Representative
    Public Property RSRID As Integer
    Public Property RSRName As String
    Public Property Active_Flag As Nullable(Of Boolean)
    Public Property SystemOnly As Nullable(Of Boolean)
    Public Property RSRSourcecode As String
    Public Property CountryID As String

End Class
