'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class M05_Branch
    Public Property BranchID As Integer
    Public Property BranchName As String
    Public Property Active_Flag As Nullable(Of Boolean)
    Public Property SystemOnly As Nullable(Of Boolean)
    Public Property CostCenter As String
    Public Property BenefitCenter As String
    Public Property DataWarehouseCenter As String
    Public Property ExpenseCenter As String

End Class
